### ISSUE TITLE
User coin storage

### ISSUE THREAD

**Issue by ddarrenc** [Dayana20/monitoring-crypto#3]
Might need to change how coins are stored into the user, currently storing an instance of 'Bitcoin' dict which will be hard to keep track of as its attributes like price change, (e.g. can't remove if price updates from API call as everything stored will be outdated).

**Comment by Dayana20** [comment]
I was thinking we could just store the name or symbol of the coin and when the user checks on the coin then we could use the API so everything will be up to date. Or do you mean the coin db because that could get outdated?

**Comment by ddarrenc** [comment]
Yeah I think storing just the name/symbol is good, I saw one of the tests was storing the entire coin_type dictionary into the list of a user and I was having issues removing it:

{'Bitcoin': {'id': 1, 'name': 'Bitcoin', 'symbol': 'BTC',
             'price': 20237.84301693455}, 'Litecoin': {'id': 2,
             'name': 'Litecoin', 'symbol': 'LTC', 'price': 62.885530866205976}}

 But if we are storing just the name/ticker ("BTC"/"BITCOIN") we should be okay!
